#!/bin/bash

tmp=/tmp/list.$$
get=/tmp/get.$$

find `pwd` -mindepth 1 > ${tmp}
local=$(pwd)
for i in $(cat ${tmp}); do
	if [ ! -d "${i}" ]; then
		echo "${i}" | sed "s|$local|.|" >> ${get}
	fi
done


for mfile in $(cat ${get});do
	s="${mfile}"; frasa=""
	let point=${#s}-3
	for(( i=0; ${i} < ${#s}; i++ )); do
		if [ ${point} -eq ${i} ];then break; fi 
		variable=${s:$i:1}
		case $variable in
			a)
				res="а"
				;;
			b)
				res="б"
				;;
			c)
				if [ "${s:$(( i+1 )):1}" = "h" ]; then
					(( i++ ))
					res="ч"
				else
					res="ц"
				fi
				;;
			d)
				res="д"
				;;
			e)
				res="е"
				;;
			f)
				res="ф"
				;;
			g)
				res="г"
				;;
			h)
				res="х"
				;;
			i)
				a="${s:$(( i+1 )):1}"
				if [ "${a}" = "a" ]; then
					(( i++ ))
					res="я"
				else
					res="и"
				fi
				;;
			j)
				a="${s:$(( i+1 )):1}"
				if [ "${a}" = "a" ]; then
					(( i++ ))
					res="я"
				else
					res="й"
				fi
				;;
			k)
				res="к"
				;;
			l)
				res="л"
				;;
			m)
				res="м"
				;;
			n)
				res="н"
				;;
			o)
				res="о"
				;;
			p)
				res="п"
				;;
			q)
				res="ку"
				;;
			r)
				res="р"
				;;
			s)
				a="${s:$(( i+1 )):1}"
				b="${s:$(( i+2 )):1}"
				if [ "${a}" = "h" ]; then
					(( i++ ))
					res="ш"
				elif [[ "${a}" = "c" && "${b}" = "h" ]]; then
					(( i+=2 ))
					res="щ"
				else
					res="с"
				fi
				;;
			t)
				res="т"
				;;
			u)
				res="у"
				;;
			v)
				res="в"
				;;
			w)
				res="в"
				;;
			x)
				res="кс"
				;;
			y)
				if [ "${s:$(( i+1 )):1}" = "u" ]; then
					(( i++ ))
					res="ю"
				elif [ "${s:$(( i+1 )):1}" = "a" ]; then
					(( i++ ))
					res="я"
				else
					u=$((${#frasa}-1))
					a=${frasa:$u:1}
					# после согласных символ "y" обычно имеет нотацию "ы", а после гласных "й"
					case ${a} in
						"б"|"в"|"г"|"д"|"ж"|"з"|"к"|"л"|"м"|"н"|"п"|"р"|"с"|"т"|"ф"|"х"|"ц"|"ч"|"ш"|"щ")
							res="ы"
							;;
						*)
							res="й"
							;;
					esac
				fi
				;;
			z)
				if [ "${s:$(( i+1 )):1}" = "h" ]; then
					(( i++ ))
					res="ж"
				else
					res="з"
				fi
				;;
# Заглавные букави
			A)
				res="А"
				;;
			B)
				res="Б"
				;;
			C)
				if [ "${s:$(( i+1 )):1}" = "H" ]; then
					(( i++ ))
					res="Ч"
				else
					res="Ц"
				fi
				;;
			D)
				res="Д"
				;;
			E)
				res="Е"
				;;
			F)
				res="Ф"
				;;
			G)
				res="Г"
				;;
			H)
				res="Х"
				;;
			I)
				a="${s:$(( i+1 )):1}"
				if [ "${a}" = "A" ]; then
					(( i++ ))
					res="Я"
				else
					res="И"
				fi
				;;
			J)
				a="${s:$(( i+1 )):1}"
				if [ "${a}" = "A" ]; then
					(( i++ ))
					res="Я"
				else
					res="Й"
				fi
				;;
			K)
				res="Л"
				;;
			L)
				res="Л"
				;;
			M)
				res="М"
				;;
			N)
				res="Н"
				;;
			O)
				res="О"
				;;
			P)
				res="П"
				;;
			Q)
				res="КУ"
				;;
			R)
				res="Р"
				;;
			S)
				a="${s:$(( i+1 )):1}"
				b="${s:$(( i+2 )):1}"
				if [ "${a}" = "H" ]; then
					(( i++ ))
					res="Ш"
				elif [[ "${a}" = "C" && "${b}" = "H" ]]; then
					(( i+=2 ))
					res="Щ"
				else
					res="С"
				fi
				;;
			T)
				res="Т"
				;;
			U)
				res="У"
				;;
			V)
				res="В"
				;;
			W)
				res="В"
				;;
			X)
				res="КС"
				;;
			Y)
				if [ "${s:$(( i+1 )):1}" = "u" ]; then
					(( i++ ))
					res="Ю"
				elif [ "${s:$(( i+1 )):1}" = "a" ]; then
					(( i++ ))
					res="Я"
				else
					u=$((${#frasa}-1))
					a=${frasa:$u:1}
					case ${a} in
						"Б"|"В"|"Г"|"Д"|"Ж"|"З"|"К"|"Л"|"М"|"Н"|"П"|"Р"|"С"|"Т"|"Ф"|"Х"|"Ц"|"Ч"|"Ш"|"Щ")
							res="Ы"
							;;
						*)
							res="Й"
							;;
					esac
				fi
				;;
			Z)
				if [ "${s:$(( i+1 )):1}" = "H" ]; then
					(( i++ ))
					res="Ж"
				else
					res="З"
				fi
				;;
			-)
				res="_"
				;;
			*)
				res=${variable}
				;;
		esac
		frasa="${frasa}${res}"
	done
	nfile=${frasa}$(echo ${mfile}|tail -c 4)
	echo ${mfile}
	echo ${nfile}
	dir=$(dirname "${nfile}");
	mkdir -p "${dir}"
	echo "${dir}"

# следующая команда лишь иммитирует реальный, на деле создается пустой файл
	touch ${nfile}
# раcкомментируй следующую строчку, если не стрёмно реально все переместить и переименовать=)
#	mv "${mfile}" "${nfile}"

done
rm ${tmp} ${get}
